# Aktobe120

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
X = pd.read_csv("../data/preprocessed/aktobe120/aktobe120_X.csv")
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   MD                       339 non-null    float64
 1   Incl.                    339 non-null    float64
 2   Azim.                    339 non-null    float64
 3   Sub-Sea                  339 non-null    float64
 4   TVD                      339 non-null    float64
 5   Local N Coord            339 non-null    float64
 6   Local E Coord            339 non-null    float64
 7   Global N Coord           339 non-null    float64
 8   Global E Coord           339 non-null    float64
 9   Dogleg                   339 non-null    float64
 10  Vertical Section         339 non-null    float64
 11  Body_OD                  339 non-null    float64
 12  Body_ID                  339 non-null    float64
 13  Body_AvgJointLength      339 non-null    float64
 14  Stabilizer_Length        339 non-null    float64
 15  Stabilizer_OD            339 non-null    float64
 16  Stabilizer_ID            339 non-null    float64
 17  Weight                   339 non-null    float64
 18  Coefficient of Friction  339 non-null    float64
 19  Minimum Yield Stress     339 non-null    int64
dtypes: float64(19), int64(1)
memory usage: 53.1 KB

In [3]:
X.head()

,MD,Incl.,Azim.,Sub-Sea,TVD,Local N Coord,Local E Coord,Global N Coord,Global E Coord,Dogleg,Vertical Section,Body_OD,Body_ID,Body_AvgJointLength,Stabilizer_Length,Stabilizer_OD,Stabilizer_ID,Weight,Coefficient of Friction,Minimum Yield Stress
0,100.0,0.300,108.180,117.368,100.000,-0.082,0.249,5089454.418,9691423.939,0.090,0.01,101.6,82.3,9.144,0.433,138.91,76.2,26.41,0.25,105
1,110.0,0.411,92.123,127.367,109.999,-0.091,0.309,5089454.409,9691423.999,0.445,0.02,101.6,82.3,9.144,0.433,138.91,76.2,26.41,0.25,105
2,120.0,0.360,88.348,137.367,119.999,-0.092,0.377,5089454.408,9691424.067,0.171,0.04,101.6,82.3,9.144,0.433,138.91,76.2,26.41,0.25,105
3,130.0,0.273,93.810,147.367,129.999,-0.092,0.432,5089454.408,9691424.122,0.275,0.06,101.6,82.3,9.144,0.433,138.91,76.2,26.41,0.25,105
4,140.0,0.263,104.222,157.367,139.999,-0.100,0.478,5089454.400,9691424.168,0.149,0.07,101.6,82.3,9.144,0.433,138.91,76.2,26.41,0.25,105

In [4]:
X[["Coefficient of Friction", "Minimum Yield Stress"]] = X[["Coefficient of Friction", "Minimum Yield Stress"]].applymap(lambda x: float(x.replace(",", ".")))

AttributeError: 'float' object has no attribute 'replace'

## Вес на крюке

In [13]:
Y_ves = pd.read_csv("../data/preprocessed/aktobe120/aktobe120_Y_ves_na_kru.csv")
Y_ves = Y_ves.rename({"Измеренная глубина рейса" : "MD"}, axis=1)
#Y_ves["MD"] = Y_ves["MD"].str.replace(",", "").astype(float)
Y_ves['MD'] = Y_ves['MD'].astype(float)

Y_ves.head(5)

,MD,Спуск,Подъём,Бурение ротором,Бурение ГЗД,Мин. вес до спирального изгиба (спуск),Макс. вес до предела текучести (подъём),Грузоподъёмность вышки
0,2359.0,59.80,71.92,59.40,57.01,52.06,132.07,225
1,2409.0,59.19,72.11,59.23,56.10,54.22,131.98,225
2,2459.0,58.40,72.72,59.14,55.26,53.84,132.81,225
3,2509.0,58.14,72.85,59.13,54.93,53.56,132.74,225
4,2559.0,58.86,74.26,60.09,55.76,53.61,132.29,225

In [14]:
target_cols = list(set(Y_ves.columns) - set(["MD"]))
Y_ves.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   MD                                       13 non-null     float64
 1   Спуск                                    13 non-null     float64
 2   Подъём                                   13 non-null     float64
 3   Бурение ротором                          13 non-null     float64
 4   Бурение ГЗД                              13 non-null     float64
 5   Мин. вес до спирального изгиба (спуск)   13 non-null     float64
 6   Макс. вес до предела текучести (подъём)  13 non-null     float64
 7   Грузоподъёмность вышки                   13 non-null     int64
dtypes: float64(7), int64(1)
memory usage: 964.0 bytes

In [15]:
X_ves = X[(X["MD"] >= Y_ves["MD"].min()) & (X["MD"] <= Y_ves["MD"].max())]
X_ves.head()

,MD,Incl.,Azim.,Sub-Sea,TVD,Local N Coord,Local E Coord,Global N Coord,Global E Coord,Dogleg,Vertical Section,Body_OD,Body_ID,Body_AvgJointLength,Stabilizer_Length,Stabilizer_OD,Stabilizer_ID,Weight,Coefficient of Friction,Minimum Yield Stress
279,2360.0,79.072,19.082,2237.354,2219.986,265.024,99.122,5089719.524,9691522.812,5.0,282.94,88.9,66.09,9.144,0.469,119.86,53.98,25.12,0.3,105
280,2370.0,80.699,18.712,2239.110,2221.742,274.338,102.310,5089728.838,9691526.000,5.0,292.79,88.9,66.09,9.144,0.469,119.86,53.98,25.12,0.3,105
281,2380.0,82.326,18.346,2240.586,2223.218,283.716,105.453,5089738.216,9691529.143,5.0,302.67,88.9,66.09,9.144,0.469,119.86,53.98,25.12,0.3,105
282,2390.0,83.953,17.982,2241.781,2224.412,293.149,108.548,5089747.649,9691532.238,5.0,312.60,88.9,66.09,9.144,0.469,119.86,53.98,25.12,0.3,105
283,2400.0,85.580,17.621,2242.693,2225.325,302.630,111.592,5089757.130,9691535.282,5.0,322.55,88.9,66.09,9.144,0.469,119.86,53.98,25.12,0.3,105

In [16]:
df = pd.merge_asof(X_ves, Y_ves, on="MD", direction="nearest")
df.head()

,MD,Incl.,Azim.,Sub-Sea,TVD,Local N Coord,Local E Coord,Global N Coord,Global E Coord,Dogleg,...,Weight,Coefficient of Friction,Minimum Yield Stress,Спуск,Подъём,Бурение ротором,Бурение ГЗД,Мин. вес до спирального изгиба (спуск),Макс. вес до предела текучести (подъём),Грузоподъёмность вышки
0,2360.0,79.072,19.082,2237.354,2219.986,265.024,99.122,5089719.524,9691522.812,5.0,...,25.12,0.3,105,59.80,71.92,59.40,57.01,52.06,132.07,225
1,2370.0,80.699,18.712,2239.110,2221.742,274.338,102.310,5089728.838,9691526.000,5.0,...,25.12,0.3,105,59.80,71.92,59.40,57.01,52.06,132.07,225
2,2380.0,82.326,18.346,2240.586,2223.218,283.716,105.453,5089738.216,9691529.143,5.0,...,25.12,0.3,105,59.80,71.92,59.40,57.01,52.06,132.07,225
3,2390.0,83.953,17.982,2241.781,2224.412,293.149,108.548,5089747.649,9691532.238,5.0,...,25.12,0.3,105,59.19,72.11,59.23,56.10,54.22,131.98,225
4,2400.0,85.580,17.621,2242.693,2225.325,302.630,111.592,5089757.130,9691535.282,5.0,...,25.12,0.3,105,59.19,72.11,59.23,56.10,54.22,131.98,225

In [17]:
df[target_cols]

,Бурение ротором,Грузоподъёмность вышки,Макс. вес до предела текучести (подъём),Бурение ГЗД,Подъём,Мин. вес до спирального изгиба (спуск),Спуск
0,59.40,225,132.07,57.01,71.92,52.06,59.80
1,59.40,225,132.07,57.01,71.92,52.06,59.80
2,59.40,225,132.07,57.01,71.92,52.06,59.80
3,59.23,225,131.98,56.10,72.11,54.22,59.19
4,59.23,225,131.98,56.10,72.11,54.22,59.19
5,59.23,225,131.98,56.10,72.11,54.22,59.19
6,59.23,225,131.98,56.10,72.11,54.22,59.19
7,59.23,225,131.98,56.10,72.11,54.22,59.19
8,59.23,225,131.98,56.10,72.11,54.22,59.19
9,59.14,225,132.81,55.26,72.72,53.84,58.40
10,59.14,225,132.81,55.26,72.72,53.84,58.40
11,59.14,225,132.81,55.26,72.72,53.84,58.40
12,59.14,225,132.81,55.26,72.72,53.84,58.40
13,59.14,225,132.81,55.26,72.72,53.84,58.40
14,59.14,225,132.81,55.26,72.72,53.84,58.40
15,59.13,225,132.74,54.93,72.85,53.56,58.14
16,59.13,225,132.74,54.93,72.85,53.56,58.14
17,59.13,225,132.74,54.93,72.85,53.56,58.14
18,59.13,225,132.74,54.93,72.85,53.56,58.14
19,59.13,225,132.74,54.93,72.85,53.56,58.14
20,60.09,225,132.29,55.76,74.26,53.61,58.86
21,60.09,225,132.29,55.76,74.26,53.61,58.86
22,60.09,225,132.29,55.76,74.26,53.61,58.86
23,60.09,225,132.29,55.76,74.26,53.61,58.86
24,60.09,225,132.29,55.76,74.26,53.61,58.86
25,60.07,225,133.11,55.02,74.98,53.26,58.13
26,60.07,225,133.11,55.02,74.98,53.26,58.13
27,60.07,225,133.11,55.02,74.98,53.26,58.13
28,60.07,225,133.11,55.02,74.98,53.26,58.13
29,60.07,225,133.11,55.02,74.98,53.26,58.13
30,59.99,225,132.98,54.68,75.02,53.59,57.82
31,59.99,225,132.98,54.68,75.02,53.59,57.82
32,59.99,225,132.98,54.68,75.02,53.59,57.82
33,59.99,225,132.98,54.68,75.02,53.59,57.82
34,59.99,225,132.98,54.68,75.02,53.59,57.82
35,59.91,225,132.90,54.02,75.61,53.37,57.21
36,59.91,225,132.90,54.02,75.61,53.37,57.21
37,59.91,225,132.90,54.02,75.61,53.37,57.21
38,59.91,225,132.90,54.02,75.61,53.37,57.21
39,59.91,225,132.90,54.02,75.61,53.37,57.21
40,59.82,225,132.83,53.74,75.57,49.69,57.00
41,59.82,225,132.83,53.74,75.57,49.69,57.00
42,59.82,225,132.83,53.74,75.57,49.69,57.00
43,59.82,225,132.83,53.74,75.57,49.69,57.00
44,59.82,225,132.83,53.74,75.57,49.69,57.00
45,59.72,225,133.27,52.74,76.64,49.47,55.95
46,59.72,225,133.27,52.74,76.64,49.47,55.95
47,59.72,225,133.27,52.74,76.64,49.47,55.95
48,59.72,225,133.27,52.74,76.64,49.47,55.95
49,59.72,225,133.27,52.74,76.64,49.47,55.95
50,59.57,225,133.19,52.45,76.43,50.91,55.66
51,59.57,225,133.19,52.45,76.43,50.91,55.66
52,59.57,225,133.19,52.45,76.43,50.91,55.66
53,59.57,225,133.19,52.45,76.43,50.91,55.66
54,59.57,225,133.19,52.45,76.43,50.91,55.66
55,59.36,225,132.62,51.71,76.60,51.11,54.95
56,59.36,225,132.62,51.71,76.60,51.11,54.95
57,59.36,225,132.62,51.71,76.60,51.11,54.95
58,59.27,225,132.59,51.42,76.74,50.41,54.66
59,59.27,225,132.59,51.42,76.74,50.41,54.66